// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 02.05.2012 11:24:53 from Type Library described below.

// ************************************************************************  //
// Type Lib: D:\Program Files (x86)\Borland\CBuilder6\Projects\H_A_Sockets\Server\Sample\Server.tlb (1)
// LIBID: {22FD94F8-3ADB-429C-B80F-17DB209F386E}
// LCID: 0
// Helpfile: 
// HelpString: Server Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// ************************************************************************ //
#ifndef   Server_TLBH
#define   Server_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif


// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Server_tlb
{

// *********************************************************************//
// HelpString: Server Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern "C" const __declspec(selectany) GUID LIBID_Server = {0x22FD94F8, 0x3ADB, 0x429C,{ 0xB8, 0x0F, 0x17,0xDB, 0x20, 0x9F,0x38, 0x6E} };
extern "C" const __declspec(selectany) GUID IID_IClients = {0x2FD5E67A, 0xF061, 0x46B6,{ 0xB0, 0xDB, 0x13,0x4D, 0x45, 0x0E,0x76, 0xAC} };
extern "C" const __declspec(selectany) GUID CLSID_Clients = {0x67022A35, 0x7BDB, 0x48B0,{ 0xBF, 0x37, 0xA0,0x4F, 0x58, 0x7E,0xB5, 0xC5} };
extern "C" const __declspec(selectany) GUID IID_ITables = {0x3AF8D7F1, 0x0DAB, 0x415C,{ 0xA0, 0x63, 0x2B,0xCE, 0x1F, 0x07,0x1E, 0x24} };
extern "C" const __declspec(selectany) GUID CLSID_Tables = {0x70589E3D, 0x2EDF, 0x4F04,{ 0xAA, 0x29, 0xB5,0x1C, 0xAD, 0xD1,0x4B, 0x23} };
extern "C" const __declspec(selectany) GUID IID_IForm = {0xBB8D688F, 0xAD99, 0x41A7,{ 0x8B, 0xFC, 0x06,0x78, 0x31, 0x94,0x51, 0x05} };
extern "C" const __declspec(selectany) GUID CLSID_Form = {0x756F9076, 0x0DC9, 0x4474,{ 0x8E, 0xC1, 0x77,0xF3, 0x66, 0x88,0x66, 0x98} };

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{2FD5E67A-F061-46B6-B0DB-134D450E76AC}") IClients;
typedef TComInterface<IClients, &IID_IClients> IClientsPtr;

interface DECLSPEC_UUID("{3AF8D7F1-0DAB-415C-A063-2BCE1F071E24}") ITables;
typedef TComInterface<ITables, &IID_ITables> ITablesPtr;

interface DECLSPEC_UUID("{BB8D688F-AD99-41A7-8BFC-067831945105}") IForm;
typedef TComInterface<IForm, &IID_IForm> IFormPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//
typedef IClients Clients;
typedef IClientsPtr ClientsPtr;
typedef ITables Tables;
typedef ITablesPtr TablesPtr;
typedef IForm Form;
typedef IFormPtr FormPtr;

#define LIBID_OF_Clients (&LIBID_Server)
#define LIBID_OF_Tables (&LIBID_Server)
#define LIBID_OF_Form (&LIBID_Server)
// *********************************************************************//
// Interface: IClients
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {2FD5E67A-F061-46B6-B0DB-134D450E76AC}
// *********************************************************************//
interface IClients  : public IDispatch
{
public:
  virtual HRESULT STDMETHODCALLTYPE Connect(BSTR CLName/*[in]*/, BSTR Login/*[in]*/, 
                                            long* IDC/*[out]*/, int* OK/*[out]*/) = 0; // [1]
  virtual HRESULT STDMETHODCALLTYPE Disconnect_IDC(long* IDC/*[out]*/, int* OK/*[out]*/) = 0; // [2]
  virtual HRESULT STDMETHODCALLTYPE Disconnect_Name(BSTR CLName/*[in]*/, int* OK/*[out,retval]*/) = 0; // [3]
  virtual HRESULT STDMETHODCALLTYPE get_CountClients(long* Count/*[out,retval]*/) = 0; // [4]
  virtual HRESULT STDMETHODCALLTYPE DisconnectAll(int* OK/*[out,retval]*/) = 0; // [5]
  virtual HRESULT STDMETHODCALLTYPE AddDatabase(long IDC/*[in]*/, BSTR Name/*[in]*/, 
                                                long* IDDB/*[out]*/) = 0; // [6]
  virtual HRESULT STDMETHODCALLTYPE get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                        int* Connect/*[out,retval]*/) = 0; // [8]
  virtual HRESULT STDMETHODCALLTYPE set_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                        int Connect/*[in]*/) = 0; // [8]
  virtual HRESULT STDMETHODCALLTYPE set_SetCommandText(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                       BSTR Param3/*[in]*/) = 0; // [7]
  virtual HRESULT STDMETHODCALLTYPE CommandExec(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                int* OK/*[out]*/) = 0; // [9]
  virtual HRESULT STDMETHODCALLTYPE MergeLogins(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                int* OK/*[out]*/, int* Wait/*[out]*/) = 0; // [10]
  virtual HRESULT STDMETHODCALLTYPE VerifyConnect(long IDC/*[in]*/) = 0; // [11]
  virtual HRESULT STDMETHODCALLTYPE get_NetError(VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [12]
  virtual HRESULT STDMETHODCALLTYPE PrepareReadMetod(long IDC/*[in]*/, BSTR NameDatabase/*[in]*/, 
                                                     int* Ret/*[out]*/) = 0; // [13]
  virtual HRESULT STDMETHODCALLTYPE MergeNodeBranch(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                                    BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                                    BSTR NameDatabase2/*[in]*/, 
                                                    BSTR NameTable/*[in]*/, BSTR NameField/*[in]*/, 
                                                    BSTR NameKey/*[in]*/, BSTR Name/*[in]*/, 
                                                    int* Ret/*[out]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE MergeNodeBranch_Sm(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                                       BSTR NameNode/*[in]*/, 
                                                       BSTR NameBranch/*[in]*/, int* Ret/*[out]*/) = 0; // [15]
  virtual HRESULT STDMETHODCALLTYPE MergeZn(long IDC/*[in]*/, BSTR Database1/*[in]*/, 
                                            BSTR Database2/*[in]*/, int* Ret/*[out]*/) = 0; // [16]
  virtual HRESULT STDMETHODCALLTYPE SaveMetod(long IDC/*[in]*/, BSTR Database/*[in]*/, 
                                              int* Ret/*[out]*/) = 0; // [17]
  virtual HRESULT STDMETHODCALLTYPE SavePodr(long IDC/*[in]*/, BSTR DB1/*[in]*/, int* Ret/*[out]*/) = 0; // [18]
  virtual HRESULT STDMETHODCALLTYPE SaveSit(long IDC/*[in]*/, BSTR DB1/*[in]*/, BSTR DB2/*[in]*/, 
                                            int* Ret/*[out]*/) = 0; // [20]
  virtual HRESULT STDMETHODCALLTYPE Visible(void) = 0; // [21]
  virtual HRESULT STDMETHODCALLTYPE MergeAspectsMainSpec(long IDC/*[in]*/, int* Ret/*[out]*/) = 0; // [22]
  virtual HRESULT STDMETHODCALLTYPE PrepareLoadAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                       long Podr/*[in]*/, long Width1/*[in]*/, 
                                                       long Width2/*[in]*/, long Width3/*[in]*/, 
                                                       long Width4/*[in]*/, int* Ret/*[out]*/) = 0; // [23]
  virtual HRESULT STDMETHODCALLTYPE get_Block(long IDC/*[in]*/, int* Value/*[out,retval]*/) = 0; // [19]
  virtual HRESULT STDMETHODCALLTYPE set_Block(long IDC/*[in]*/, int* Value/*[in,out]*/) = 0; // [19]
  virtual HRESULT STDMETHODCALLTYPE PrepareMergeAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                        long NumLogin/*[in]*/, long W1/*[in]*/, 
                                                        long W2/*[in]*/, long W3/*[in]*/, 
                                                        long W4/*[in]*/, int* Ret/*[out]*/) = 0; // [24]
  virtual HRESULT STDMETHODCALLTYPE WriteDiary(BSTR Comp/*[in]*/, BSTR Login/*[in]*/, 
                                               BSTR Type/*[in]*/, BSTR Name/*[in]*/, 
                                               BSTR Prim/*[in]*/) = 0; // [25]
  virtual HRESULT STDMETHODCALLTYPE get_LicenseCount(BSTR DBName/*[in]*/, 
                                                     long* Value/*[out,retval]*/) = 0; // [26]
  virtual HRESULT STDMETHODCALLTYPE PrepareMergeAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                         long NumLogin/*[in]*/, long W1/*[in]*/, 
                                                         long W2/*[in]*/, long W3/*[in]*/, 
                                                         long W4/*[in]*/, int* Ret/*[out]*/) = 0; // [28]
  virtual HRESULT STDMETHODCALLTYPE PrepareLoadAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                        long Podr/*[in]*/, long Width1/*[in]*/, 
                                                        long Width2/*[in]*/, long Width3/*[in]*/, 
                                                        long Width4/*[in]*/, int* Ret/*[out]*/) = 0; // [29]
  virtual HRESULT STDMETHODCALLTYPE MergeAspectsMainSpecH(long IDC/*[in]*/, int* Ret/*[out]*/) = 0; // [30]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  int __fastcall Disconnect_Name(BSTR CLName/*[in]*/)
  {
    int OK;
    OLECHECK(this->Disconnect_Name(CLName, (int*)&OK));
    return OK;
  }

  long __fastcall get_CountClients(void)
  {
    long Count;
    OLECHECK(this->get_CountClients((long*)&Count));
    return Count;
  }

  int __fastcall DisconnectAll(void)
  {
    int OK;
    OLECHECK(this->DisconnectAll((int*)&OK));
    return OK;
  }

  int __fastcall get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/)
  {
    int Connect;
    OLECHECK(this->get_DatabaseConnect(IDC, IDDB, (int*)&Connect));
    return Connect;
  }

  VARIANT_BOOL __fastcall get_NetError(void)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_NetError((VARIANT_BOOL*)&Value));
    return Value;
  }

  int __fastcall get_Block(long IDC/*[in]*/)
  {
    int Value;
    OLECHECK(this->get_Block(IDC, (int*)&Value));
    return Value;
  }

  long __fastcall get_LicenseCount(BSTR DBName/*[in]*/)
  {
    long Value;
    OLECHECK(this->get_LicenseCount(DBName, (long*)&Value));
    return Value;
  }


  __property   long            CountClients = {read = get_CountClients};
  __property   VARIANT_BOOL    NetError = {read = get_NetError};

#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: ITables
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {3AF8D7F1-0DAB-415C-A063-2BCE1F071E24}
// *********************************************************************//
interface ITables  : public IDispatch
{
public:
  virtual HRESULT STDMETHODCALLTYPE CreateTable(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                long IDF/*[in]*/, long* IDT/*[out]*/) = 0; // [1]
  virtual HRESULT STDMETHODCALLTYPE DeleteTable(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                                int* OK/*[out]*/) = 0; // [2]
  virtual HRESULT STDMETHODCALLTYPE Active(VARIANT_BOOL Value/*[in]*/, long IDC/*[in]*/, 
                                           long IDF/*[in]*/, long IDT/*[in]*/, int* OK/*[out]*/) = 0; // [3]
  virtual HRESULT STDMETHODCALLTYPE get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, 
                                                    long IDT/*[in]*/, BSTR* Text/*[out,retval]*/) = 0; // [4]
  virtual HRESULT STDMETHODCALLTYPE set_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, 
                                                    long IDT/*[in]*/, BSTR Text/*[in]*/) = 0; // [4]
  virtual HRESULT STDMETHODCALLTYPE Moving(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                           long IDT/*[in]*/) = 0; // [5]
  virtual HRESULT STDMETHODCALLTYPE get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, 
                                                long IDF/*[in]*/, long IDT/*[in]*/, 
                                                VARIANT_BOOL* Value/*[out,retval]*/) = 0; // [6]
  virtual HRESULT STDMETHODCALLTYPE get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                            long IDF/*[in]*/, long IDT/*[in]*/, 
                                                            VARIANT* Value/*[out,retval]*/) = 0; // [7]
  virtual HRESULT STDMETHODCALLTYPE set_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                            long IDF/*[in]*/, long IDT/*[in]*/, 
                                                            VARIANT Value/*[in]*/) = 0; // [7]
  virtual HRESULT STDMETHODCALLTYPE EditingRecord(long Comand/*[in]*/, long IDC/*[in]*/, 
                                                  long IDF/*[in]*/, long IDT/*[in]*/) = 0; // [8]
  virtual HRESULT STDMETHODCALLTYPE get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, 
                                                    long IDT/*[in]*/, long* Value/*[out,retval]*/) = 0; // [10]
  virtual HRESULT STDMETHODCALLTYPE get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                              long* Value/*[out,retval]*/) = 0; // [9]
  virtual HRESULT STDMETHODCALLTYPE Move(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                         long Step/*[in]*/) = 0; // [11]
  virtual HRESULT STDMETHODCALLTYPE get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                               BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, 
                                               long SearchParam/*[in]*/, 
                                               VARIANT_BOOL* OK/*[out,retval]*/) = 0; // [12]
  virtual HRESULT STDMETHODCALLTYPE Delete(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/) = 0; // [13]
  virtual HRESULT STDMETHODCALLTYPE get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, 
                                               long IDF/*[in]*/, long IDT/*[in]*/, 
                                               VARIANT* Value/*[out,retval]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE set_Fields(long NumField/*[in]*/, long IDC/*[in]*/, 
                                               long IDF/*[in]*/, long IDT/*[in]*/, 
                                               VARIANT Value/*[in]*/) = 0; // [14]
  virtual HRESULT STDMETHODCALLTYPE get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, 
                                                    long IDT/*[in]*/, long* Value/*[out,retval]*/) = 0; // [15]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  BSTR __fastcall get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
  {
    BSTR Text = 0;
    OLECHECK(this->get_CommandText(IDC, IDF, IDT, (BSTR*)&Text));
    return Text;
  }

  VARIANT_BOOL __fastcall get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                      long IDT/*[in]*/)
  {
    VARIANT_BOOL Value;
    OLECHECK(this->get_BOF_EOF(Comand, IDC, IDF, IDT, (VARIANT_BOOL*)&Value));
    return Value;
  }

  VARIANT __fastcall get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                             long IDF/*[in]*/, long IDT/*[in]*/)
  {
    VARIANT Value;
    OLECHECK(this->get_FieldByName_Variant(FieldName, IDC, IDF, IDT, (VARIANT*)&Value));
    return Value;
  }

  long __fastcall get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
  {
    long Value;
    OLECHECK(this->get_RecordCount(IDC, IDF, IDT, (long*)&Value));
    return Value;
  }

  long __fastcall get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
  {
    long Value;
    OLECHECK(this->get_RecNo(IDC, IDF, IDT, (long*)&Value));
    return Value;
  }

  VARIANT_BOOL __fastcall get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                     BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, 
                                     long SearchParam/*[in]*/)
  {
    VARIANT_BOOL OK;
    OLECHECK(this->get_Locate(IDC, IDF, IDT, FieldName, Key, SearchParam, (VARIANT_BOOL*)&OK));
    return OK;
  }

  VARIANT __fastcall get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                long IDT/*[in]*/)
  {
    VARIANT Value;
    OLECHECK(this->get_Fields(NumField, IDC, IDF, IDT, (VARIANT*)&Value));
    return Value;
  }

  long __fastcall get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
  {
    long Value;
    OLECHECK(this->get_FieldsCount(IDC, IDF, IDT, (long*)&Value));
    return Value;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

// *********************************************************************//
// Interface: IForm
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {BB8D688F-AD99-41A7-8BFC-067831945105}
// *********************************************************************//
interface IForm  : public IDispatch
{
public:
  virtual HRESULT STDMETHODCALLTYPE RegForm(long IDC/*[in]*/, BSTR NameForm/*[in]*/, 
                                            long* IDF/*[out]*/, int* OK/*[in,out,opt]*/) = 0; // [1]
  virtual HRESULT STDMETHODCALLTYPE UnregForm_IDF(long IDC/*[in]*/, long IDF/*[in]*/, 
                                                  int* OK/*[in,out,opt]*/) = 0; // [2]
  virtual HRESULT STDMETHODCALLTYPE UnregForm_Name(long IDC/*[in]*/, BSTR NameForm/*[in]*/, 
                                                   int* OK/*[in,out,opt]*/) = 0; // [3]
  virtual HRESULT STDMETHODCALLTYPE UnregAll(long IDC/*[in]*/, int* OK/*[in,out,opt]*/) = 0; // [4]
  virtual HRESULT STDMETHODCALLTYPE get_CountForm(long IDC/*[in]*/, long* Count/*[out,retval]*/) = 0; // [5]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  long __fastcall get_CountForm(long IDC/*[in]*/)
  {
    long Count;
    OLECHECK(this->get_CountForm(IDC, (long*)&Count));
    return Count;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMIClients
// Interface: IClients
// *********************************************************************//
template <class T /* IClients */ >
class TCOMIClientsT : public TComInterface<IClients>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIClientsT() {}
  TCOMIClientsT(IClients *intf, bool addRef = false) : TComInterface<IClients>(intf, addRef) {}
  TCOMIClientsT(const TCOMIClientsT& src) : TComInterface<IClients>(src) {}
  TCOMIClientsT& operator=(const TCOMIClientsT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Connect(BSTR CLName/*[in]*/, BSTR Login/*[in]*/, long* IDC/*[out]*/, 
                                     int* OK/*[out]*/);
  HRESULT         __fastcall Disconnect_IDC(long* IDC/*[out]*/, int* OK/*[out]*/);
  HRESULT         __fastcall Disconnect_Name(BSTR CLName/*[in]*/, int* OK/*[out,retval]*/);
  int             __fastcall Disconnect_Name(BSTR CLName/*[in]*/);
  HRESULT         __fastcall get_CountClients(long* Count/*[out,retval]*/);
  long            __fastcall get_CountClients(void);
  HRESULT         __fastcall DisconnectAll(int* OK/*[out,retval]*/);
  int             __fastcall DisconnectAll(void);
  HRESULT         __fastcall AddDatabase(long IDC/*[in]*/, BSTR Name/*[in]*/, long* IDDB/*[out]*/);
  HRESULT         __fastcall get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                 int* Connect/*[out,retval]*/);
  int             __fastcall get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/);
  HRESULT         __fastcall set_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                 int Connect/*[in]*/);
  HRESULT         __fastcall set_SetCommandText(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                BSTR Param3/*[in]*/);
  HRESULT         __fastcall CommandExec(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/);
  HRESULT         __fastcall MergeLogins(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/, 
                                         int* Wait/*[out]*/);
  HRESULT         __fastcall VerifyConnect(long IDC/*[in]*/);
  HRESULT         __fastcall get_NetError(VARIANT_BOOL* Value/*[out,retval]*/);
  HRESULT         __fastcall get_NetError(TOLEBOOL* Value/*[out,retval]*/);
  TOLEBOOL        __fastcall get_NetError(void);
  HRESULT         __fastcall PrepareReadMetod(long IDC/*[in]*/, BSTR NameDatabase/*[in]*/, 
                                              int* Ret/*[out]*/);
  HRESULT         __fastcall MergeNodeBranch(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                             BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                             BSTR NameDatabase2/*[in]*/, BSTR NameTable/*[in]*/, 
                                             BSTR NameField/*[in]*/, BSTR NameKey/*[in]*/, 
                                             BSTR Name/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall MergeNodeBranch_Sm(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                                BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                                int* Ret/*[out]*/);
  HRESULT         __fastcall MergeZn(long IDC/*[in]*/, BSTR Database1/*[in]*/, 
                                     BSTR Database2/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall SaveMetod(long IDC/*[in]*/, BSTR Database/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall SavePodr(long IDC/*[in]*/, BSTR DB1/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall SaveSit(long IDC/*[in]*/, BSTR DB1/*[in]*/, BSTR DB2/*[in]*/, 
                                     int* Ret/*[out]*/);
  HRESULT         __fastcall Visible(void);
  HRESULT         __fastcall MergeAspectsMainSpec(long IDC/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall PrepareLoadAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                long Podr/*[in]*/, long Width1/*[in]*/, 
                                                long Width2/*[in]*/, long Width3/*[in]*/, 
                                                long Width4/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall get_Block(long IDC/*[in]*/, int* Value/*[out,retval]*/);
  int             __fastcall get_Block(long IDC/*[in]*/);
  HRESULT         __fastcall set_Block(long IDC/*[in]*/, int* Value/*[in,out]*/);
  HRESULT         __fastcall PrepareMergeAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                 long NumLogin/*[in]*/, long W1/*[in]*/, 
                                                 long W2/*[in]*/, long W3/*[in]*/, long W4/*[in]*/, 
                                                 int* Ret/*[out]*/);
  HRESULT         __fastcall WriteDiary(BSTR Comp/*[in]*/, BSTR Login/*[in]*/, BSTR Type/*[in]*/, 
                                        BSTR Name/*[in]*/, BSTR Prim/*[in]*/);
  HRESULT         __fastcall get_LicenseCount(BSTR DBName/*[in]*/, long* Value/*[out,retval]*/);
  long            __fastcall get_LicenseCount(BSTR DBName/*[in]*/);
  HRESULT         __fastcall PrepareMergeAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                  long NumLogin/*[in]*/, long W1/*[in]*/, 
                                                  long W2/*[in]*/, long W3/*[in]*/, long W4/*[in]*/, 
                                                  int* Ret/*[out]*/);
  HRESULT         __fastcall PrepareLoadAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                 long Podr/*[in]*/, long Width1/*[in]*/, 
                                                 long Width2/*[in]*/, long Width3/*[in]*/, 
                                                 long Width4/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall MergeAspectsMainSpecH(long IDC/*[in]*/, int* Ret/*[out]*/);

  __property   long            CountClients = {read = get_CountClients};
  __property   TOLEBOOL        NetError = {read = get_NetError};
};
typedef TCOMIClientsT<IClients> TCOMIClients;

// *********************************************************************//
// DispIntf:  IClients
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {2FD5E67A-F061-46B6-B0DB-134D450E76AC}
// *********************************************************************//
template<class T>
class IClientsDispT : public TAutoDriver<IClients>
{
public:
  IClientsDispT(){}

  IClientsDispT(IClients *pintf)
  {
    TAutoDriver<IClients>::Bind(pintf, false);
  }

  IClientsDispT(IClientsPtr pintf)
  {
    TAutoDriver<IClients>::Bind(pintf, true);
  }

  IClientsDispT& operator=(IClients *pintf)
  {
    TAutoDriver<IClients>::Bind(pintf, false);
    return *this;
  }

  IClientsDispT& operator=(IClientsPtr pintf)
  {
    TAutoDriver<IClients>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_Clients));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_Clients);
  }

  HRESULT         __fastcall Connect(BSTR CLName/*[in]*/, BSTR Login/*[in]*/, long* IDC/*[out]*/, 
                                     int* OK/*[out]*/);
  HRESULT         __fastcall Disconnect_IDC(long* IDC/*[out]*/, int* OK/*[out]*/);
  HRESULT         __fastcall Disconnect_Name(BSTR CLName/*[in]*/, int* OK/*[out,retval]*/);
  int             __fastcall Disconnect_Name(BSTR CLName/*[in]*/);
  HRESULT         __fastcall get_CountClients(long* Count/*[out,retval]*/);
  long            __fastcall get_CountClients(void);
  HRESULT         __fastcall DisconnectAll(int* OK/*[out,retval]*/);
  int             __fastcall DisconnectAll(void);
  HRESULT         __fastcall AddDatabase(long IDC/*[in]*/, BSTR Name/*[in]*/, long* IDDB/*[out]*/);
  HRESULT         __fastcall get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                 int* Connect/*[out,retval]*/);
  int             __fastcall get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/);
  HRESULT         __fastcall set_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                 int Connect/*[in]*/);
  HRESULT         __fastcall set_SetCommandText(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                                BSTR Param3/*[in]*/);
  HRESULT         __fastcall CommandExec(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/);
  HRESULT         __fastcall MergeLogins(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/, 
                                         int* Wait/*[out]*/);
  HRESULT         __fastcall VerifyConnect(long IDC/*[in]*/);
  HRESULT         __fastcall get_NetError(VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_NetError(void);
  HRESULT         __fastcall PrepareReadMetod(long IDC/*[in]*/, BSTR NameDatabase/*[in]*/, 
                                              int* Ret/*[out]*/);
  HRESULT         __fastcall MergeNodeBranch(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                             BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                             BSTR NameDatabase2/*[in]*/, BSTR NameTable/*[in]*/, 
                                             BSTR NameField/*[in]*/, BSTR NameKey/*[in]*/, 
                                             BSTR Name/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall MergeNodeBranch_Sm(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                                BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                                int* Ret/*[out]*/);
  HRESULT         __fastcall MergeZn(long IDC/*[in]*/, BSTR Database1/*[in]*/, 
                                     BSTR Database2/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall SaveMetod(long IDC/*[in]*/, BSTR Database/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall SavePodr(long IDC/*[in]*/, BSTR DB1/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall SaveSit(long IDC/*[in]*/, BSTR DB1/*[in]*/, BSTR DB2/*[in]*/, 
                                     int* Ret/*[out]*/);
  HRESULT         __fastcall Visible();
  HRESULT         __fastcall MergeAspectsMainSpec(long IDC/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall PrepareLoadAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                long Podr/*[in]*/, long Width1/*[in]*/, 
                                                long Width2/*[in]*/, long Width3/*[in]*/, 
                                                long Width4/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall get_Block(long IDC/*[in]*/, int* Value/*[out,retval]*/);
  int             __fastcall get_Block(long IDC/*[in]*/);
  HRESULT         __fastcall set_Block(long IDC/*[in]*/, int* Value/*[in,out]*/);
  HRESULT         __fastcall PrepareMergeAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                 long NumLogin/*[in]*/, long W1/*[in]*/, 
                                                 long W2/*[in]*/, long W3/*[in]*/, long W4/*[in]*/, 
                                                 int* Ret/*[out]*/);
  HRESULT         __fastcall WriteDiary(BSTR Comp/*[in]*/, BSTR Login/*[in]*/, BSTR Type/*[in]*/, 
                                        BSTR Name/*[in]*/, BSTR Prim/*[in]*/);
  HRESULT         __fastcall get_LicenseCount(BSTR DBName/*[in]*/, long* Value/*[out,retval]*/);
  long            __fastcall get_LicenseCount(BSTR DBName/*[in]*/);
  HRESULT         __fastcall PrepareMergeAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                  long NumLogin/*[in]*/, long W1/*[in]*/, 
                                                  long W2/*[in]*/, long W3/*[in]*/, long W4/*[in]*/
                                                  , int* Ret/*[out]*/);
  HRESULT         __fastcall PrepareLoadAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                                 long Podr/*[in]*/, long Width1/*[in]*/, 
                                                 long Width2/*[in]*/, long Width3/*[in]*/, 
                                                 long Width4/*[in]*/, int* Ret/*[out]*/);
  HRESULT         __fastcall MergeAspectsMainSpecH(long IDC/*[in]*/, int* Ret/*[out]*/);

  __property   long            CountClients = {read = get_CountClients};
  __property   VARIANT_BOOL    NetError = {read = get_NetError};
};
typedef IClientsDispT<IClients> IClientsDisp;

// *********************************************************************//
// SmartIntf: TCOMITables
// Interface: ITables
// *********************************************************************//
template <class T /* ITables */ >
class TCOMITablesT : public TComInterface<ITables>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMITablesT() {}
  TCOMITablesT(ITables *intf, bool addRef = false) : TComInterface<ITables>(intf, addRef) {}
  TCOMITablesT(const TCOMITablesT& src) : TComInterface<ITables>(src) {}
  TCOMITablesT& operator=(const TCOMITablesT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall CreateTable(long IDC/*[in]*/, long IDDB/*[in]*/, long IDF/*[in]*/, 
                                         long* IDT/*[out]*/);
  HRESULT         __fastcall DeleteTable(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                         int* OK/*[out]*/);
  HRESULT         __fastcall Active(VARIANT_BOOL Value/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                    long IDT/*[in]*/, int* OK/*[out]*/);
  HRESULT         __fastcall get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             BSTR* Text/*[out,retval]*/);
  BSTR            __fastcall get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall set_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             BSTR Text/*[in]*/);
  HRESULT         __fastcall Moving(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                    long IDT/*[in]*/);
  HRESULT         __fastcall get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/, VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/);
  HRESULT         __fastcall get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                     long IDF/*[in]*/, long IDT/*[in]*/, 
                                                     VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                     long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall set_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                     long IDF/*[in]*/, long IDT/*[in]*/, 
                                                     VARIANT Value/*[in]*/);
  HRESULT         __fastcall EditingRecord(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                           long IDT/*[in]*/);
  HRESULT         __fastcall get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             long* Value/*[out,retval]*/);
  long            __fastcall get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                       long* Value/*[out,retval]*/);
  long            __fastcall get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall Move(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                  long Step/*[in]*/);
  HRESULT         __fastcall get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                        BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, 
                                        long SearchParam/*[in]*/, VARIANT_BOOL* OK/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                        BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, 
                                        long SearchParam/*[in]*/);
  HRESULT         __fastcall Delete(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                        long IDT/*[in]*/, VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                        long IDT/*[in]*/);
  HRESULT         __fastcall set_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                        long IDT/*[in]*/, VARIANT Value/*[in]*/);
  HRESULT         __fastcall get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             long* Value/*[out,retval]*/);
  long            __fastcall get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);

};
typedef TCOMITablesT<ITables> TCOMITables;

// *********************************************************************//
// DispIntf:  ITables
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {3AF8D7F1-0DAB-415C-A063-2BCE1F071E24}
// *********************************************************************//
template<class T>
class ITablesDispT : public TAutoDriver<ITables>
{
public:
  ITablesDispT(){}

  ITablesDispT(ITables *pintf)
  {
    TAutoDriver<ITables>::Bind(pintf, false);
  }

  ITablesDispT(ITablesPtr pintf)
  {
    TAutoDriver<ITables>::Bind(pintf, true);
  }

  ITablesDispT& operator=(ITables *pintf)
  {
    TAutoDriver<ITables>::Bind(pintf, false);
    return *this;
  }

  ITablesDispT& operator=(ITablesPtr pintf)
  {
    TAutoDriver<ITables>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_Tables));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_Tables);
  }

  HRESULT         __fastcall CreateTable(long IDC/*[in]*/, long IDDB/*[in]*/, long IDF/*[in]*/, 
                                         long* IDT/*[out]*/);
  HRESULT         __fastcall DeleteTable(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                         int* OK/*[out]*/);
  HRESULT         __fastcall Active(VARIANT_BOOL Value/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                    long IDT/*[in]*/, int* OK/*[out]*/);
  HRESULT         __fastcall get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             BSTR* Text/*[out,retval]*/);
  BSTR            __fastcall get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall set_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             BSTR Text/*[in]*/);
  HRESULT         __fastcall Moving(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                    long IDT/*[in]*/);
  HRESULT         __fastcall get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/, VARIANT_BOOL* Value/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/);
  HRESULT         __fastcall get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                     long IDF/*[in]*/, long IDT/*[in]*/, 
                                                     VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                     long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall set_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, 
                                                     long IDF/*[in]*/, long IDT/*[in]*/, 
                                                     VARIANT Value/*[in]*/);
  HRESULT         __fastcall EditingRecord(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                           long IDT/*[in]*/);
  HRESULT         __fastcall get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             long* Value/*[out,retval]*/);
  long            __fastcall get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                       long* Value/*[out,retval]*/);
  long            __fastcall get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall Move(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                  long Step/*[in]*/);
  HRESULT         __fastcall get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                        BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, 
                                        long SearchParam/*[in]*/, VARIANT_BOOL* OK/*[out,retval]*/);
  VARIANT_BOOL    __fastcall get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                        BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, 
                                        long SearchParam/*[in]*/);
  HRESULT         __fastcall Delete(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);
  HRESULT         __fastcall get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                        long IDT/*[in]*/, VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                        long IDT/*[in]*/);
  HRESULT         __fastcall set_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                        long IDT/*[in]*/, VARIANT Value/*[in]*/);
  HRESULT         __fastcall get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                             long* Value/*[out,retval]*/);
  long            __fastcall get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/);

};
typedef ITablesDispT<ITables> ITablesDisp;

// *********************************************************************//
// SmartIntf: TCOMIForm
// Interface: IForm
// *********************************************************************//
template <class T /* IForm */ >
class TCOMIFormT : public TComInterface<IForm>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIFormT() {}
  TCOMIFormT(IForm *intf, bool addRef = false) : TComInterface<IForm>(intf, addRef) {}
  TCOMIFormT(const TCOMIFormT& src) : TComInterface<IForm>(src) {}
  TCOMIFormT& operator=(const TCOMIFormT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall RegForm(long IDC/*[in]*/, BSTR NameForm/*[in]*/, long* IDF/*[out]*/, 
                                     int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall UnregForm_IDF(long IDC/*[in]*/, long IDF/*[in]*/, 
                                           int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall UnregForm_Name(long IDC/*[in]*/, BSTR NameForm/*[in]*/, 
                                            int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall UnregAll(long IDC/*[in]*/, int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall get_CountForm(long IDC/*[in]*/, long* Count/*[out,retval]*/);
  long            __fastcall get_CountForm(long IDC/*[in]*/);

};
typedef TCOMIFormT<IForm> TCOMIForm;

// *********************************************************************//
// DispIntf:  IForm
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {BB8D688F-AD99-41A7-8BFC-067831945105}
// *********************************************************************//
template<class T>
class IFormDispT : public TAutoDriver<IForm>
{
public:
  IFormDispT(){}

  IFormDispT(IForm *pintf)
  {
    TAutoDriver<IForm>::Bind(pintf, false);
  }

  IFormDispT(IFormPtr pintf)
  {
    TAutoDriver<IForm>::Bind(pintf, true);
  }

  IFormDispT& operator=(IForm *pintf)
  {
    TAutoDriver<IForm>::Bind(pintf, false);
    return *this;
  }

  IFormDispT& operator=(IFormPtr pintf)
  {
    TAutoDriver<IForm>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_Form));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_Form);
  }

  HRESULT         __fastcall RegForm(long IDC/*[in]*/, BSTR NameForm/*[in]*/, long* IDF/*[out]*/, 
                                     int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall UnregForm_IDF(long IDC/*[in]*/, long IDF/*[in]*/, 
                                           int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall UnregForm_Name(long IDC/*[in]*/, BSTR NameForm/*[in]*/, 
                                            int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall UnregAll(long IDC/*[in]*/, int* OK/*[in,out,opt]*/);
  HRESULT         __fastcall get_CountForm(long IDC/*[in]*/, long* Count/*[out,retval]*/);
  long            __fastcall get_CountForm(long IDC/*[in]*/);

};
typedef IFormDispT<IForm> IFormDisp;

// *********************************************************************//
// SmartIntf: TCOMIClients
// Interface: IClients
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIClientsT<T>::Connect(BSTR CLName/*[in]*/, BSTR Login/*[in]*/, long* IDC/*[out]*/, 
                          int* OK/*[out]*/)
{
  return (*this)->Connect(CLName, Login, IDC, OK);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::Disconnect_IDC(long* IDC/*[out]*/, int* OK/*[out]*/)
{
  return (*this)->Disconnect_IDC(IDC, OK);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::Disconnect_Name(BSTR CLName/*[in]*/, int* OK/*[out,retval]*/)
{
  return (*this)->Disconnect_Name(CLName, OK);
}

template <class T> int __fastcall
TCOMIClientsT<T>::Disconnect_Name(BSTR CLName/*[in]*/)
{
  int OK;
  OLECHECK(this->Disconnect_Name(, (int*)&OK));
  return OK;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::get_CountClients(long* Count/*[out,retval]*/)
{
  return (*this)->get_CountClients(Count);
}

template <class T> long __fastcall
TCOMIClientsT<T>::get_CountClients(void)
{
  long Count;
  OLECHECK(this->get_CountClients((long*)&Count));
  return Count;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::DisconnectAll(int* OK/*[out,retval]*/)
{
  return (*this)->DisconnectAll(OK);
}

template <class T> int __fastcall
TCOMIClientsT<T>::DisconnectAll(void)
{
  int OK;
  OLECHECK(this->DisconnectAll((int*)&OK));
  return OK;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::AddDatabase(long IDC/*[in]*/, BSTR Name/*[in]*/, long* IDDB/*[out]*/)
{
  return (*this)->AddDatabase(IDC, Name, IDDB);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                      int* Connect/*[out,retval]*/)
{
  return (*this)->get_DatabaseConnect(IDC, IDDB, Connect);
}

template <class T> int __fastcall
TCOMIClientsT<T>::get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/)
{
  int Connect;
  OLECHECK(this->get_DatabaseConnect(, (int*)&Connect));
  return Connect;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::set_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, int Connect/*[in]*/)
{
  return (*this)->set_DatabaseConnect(IDC, IDDB, Connect);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::set_SetCommandText(long IDC/*[in]*/, long IDDB/*[in]*/, BSTR Param3/*[in]*/)
{
  return (*this)->set_SetCommandText(IDC, IDDB, Param3);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::CommandExec(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/)
{
  return (*this)->CommandExec(IDC, IDDB, OK);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::MergeLogins(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/, 
                              int* Wait/*[out]*/)
{
  return (*this)->MergeLogins(IDC, IDDB, OK, Wait);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::VerifyConnect(long IDC/*[in]*/)
{
  return (*this)->VerifyConnect(IDC);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::get_NetError(VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_NetError(Value);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::get_NetError(TOLEBOOL* Value/*[out,retval]*/)
{
  return (*this)->get_NetError(VARIANT_BOOL*)Value);
}

template <class T> TOLEBOOL __fastcall
TCOMIClientsT<T>::get_NetError(void)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_NetError((VARIANT_BOOL*)&Value));
  return (TOLEBOOL)Value;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::PrepareReadMetod(long IDC/*[in]*/, BSTR NameDatabase/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->PrepareReadMetod(IDC, NameDatabase, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::MergeNodeBranch(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                  BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                  BSTR NameDatabase2/*[in]*/, BSTR NameTable/*[in]*/, 
                                  BSTR NameField/*[in]*/, BSTR NameKey/*[in]*/, BSTR Name/*[in]*/, 
                                  int* Ret/*[out]*/)
{
  return (*this)->MergeNodeBranch(IDC, NameDatabase1, NameNode, NameBranch, NameDatabase2, NameTable, 
                                  NameField, NameKey, Name, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::MergeNodeBranch_Sm(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                     BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                     int* Ret/*[out]*/)
{
  return (*this)->MergeNodeBranch_Sm(IDC, NameDatabase1, NameNode, NameBranch, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::MergeZn(long IDC/*[in]*/, BSTR Database1/*[in]*/, BSTR Database2/*[in]*/, 
                          int* Ret/*[out]*/)
{
  return (*this)->MergeZn(IDC, Database1, Database2, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::SaveMetod(long IDC/*[in]*/, BSTR Database/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->SaveMetod(IDC, Database, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::SavePodr(long IDC/*[in]*/, BSTR DB1/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->SavePodr(IDC, DB1, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::SaveSit(long IDC/*[in]*/, BSTR DB1/*[in]*/, BSTR DB2/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->SaveSit(IDC, DB1, DB2, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::Visible(void)
{
  return (*this)->Visible();
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::MergeAspectsMainSpec(long IDC/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->MergeAspectsMainSpec(IDC, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::PrepareLoadAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, long Podr/*[in]*/, 
                                     long Width1/*[in]*/, long Width2/*[in]*/, long Width3/*[in]*/, 
                                     long Width4/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->PrepareLoadAspects(NameDatabase, IDC, Podr, Width1, Width2, Width3, Width4, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::get_Block(long IDC/*[in]*/, int* Value/*[out,retval]*/)
{
  return (*this)->get_Block(IDC, Value);
}

template <class T> int __fastcall
TCOMIClientsT<T>::get_Block(long IDC/*[in]*/)
{
  int Value;
  OLECHECK(this->get_Block(, (int*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::set_Block(long IDC/*[in]*/, int* Value/*[in,out]*/)
{
  return (*this)->set_Block(IDC, Value);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::PrepareMergeAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                      long NumLogin/*[in]*/, long W1/*[in]*/, long W2/*[in]*/, 
                                      long W3/*[in]*/, long W4/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->PrepareMergeAspects(NameDatabase, IDC, NumLogin, W1, W2, W3, W4, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::WriteDiary(BSTR Comp/*[in]*/, BSTR Login/*[in]*/, BSTR Type/*[in]*/, 
                             BSTR Name/*[in]*/, BSTR Prim/*[in]*/)
{
  return (*this)->WriteDiary(Comp, Login, Type, Name, Prim);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::get_LicenseCount(BSTR DBName/*[in]*/, long* Value/*[out,retval]*/)
{
  return (*this)->get_LicenseCount(DBName, Value);
}

template <class T> long __fastcall
TCOMIClientsT<T>::get_LicenseCount(BSTR DBName/*[in]*/)
{
  long Value;
  OLECHECK(this->get_LicenseCount(, (long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::PrepareMergeAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                       long NumLogin/*[in]*/, long W1/*[in]*/, long W2/*[in]*/, 
                                       long W3/*[in]*/, long W4/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->PrepareMergeAspectsH(NameDatabase, IDC, NumLogin, W1, W2, W3, W4, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::PrepareLoadAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, long Podr/*[in]*/, 
                                      long Width1/*[in]*/, long Width2/*[in]*/, long Width3/*[in]*/, 
                                      long Width4/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->PrepareLoadAspectsH(NameDatabase, IDC, Podr, Width1, Width2, Width3, Width4, Ret);
}

template <class T> HRESULT __fastcall
TCOMIClientsT<T>::MergeAspectsMainSpecH(long IDC/*[in]*/, int* Ret/*[out]*/)
{
  return (*this)->MergeAspectsMainSpecH(IDC, Ret);
}

// *********************************************************************//
// DispIntf:  IClients
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {2FD5E67A-F061-46B6-B0DB-134D450E76AC}
// *********************************************************************//
template <class T> HRESULT __fastcall
IClientsDispT<T>::Connect(BSTR CLName/*[in]*/, BSTR Login/*[in]*/, long* IDC/*[out]*/, 
                          int* OK/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("Connect"), DISPID(1));
  TAutoArgs<4> _args;
  _args[1] = CLName /*[VT_BSTR:0]*/;
  _args[2] = Login /*[VT_BSTR:0]*/;
  _args[3] = IDC /*[VT_I4:1]*/;
  _args[4] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::Disconnect_IDC(long* IDC/*[out]*/, int* OK/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("Disconnect_IDC"), DISPID(2));
  TAutoArgs<2> _args;
  _args[1] = IDC /*[VT_I4:1]*/;
  _args[2] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::Disconnect_Name(BSTR CLName/*[in]*/, int* OK/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Disconnect_Name"), DISPID(3));
  TAutoArgs<1> _args;
  _args[1] = CLName /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(OK /*[VT_INT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> int __fastcall
IClientsDispT<T>::Disconnect_Name(BSTR CLName/*[in]*/)
{
  int OK;
  this->Disconnect_Name(CLName, (int*)&OK);
  return OK;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::get_CountClients(long* Count/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("CountClients"), DISPID(4));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Count /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
IClientsDispT<T>::get_CountClients(void)
{
  long Count;
  this->get_CountClients((long*)&Count);
  return Count;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::DisconnectAll(int* OK/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("DisconnectAll"), DISPID(5));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(OK /*[VT_INT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> int __fastcall
IClientsDispT<T>::DisconnectAll(void)
{
  int OK;
  this->DisconnectAll((int*)&OK);
  return OK;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::AddDatabase(long IDC/*[in]*/, BSTR Name/*[in]*/, long* IDDB/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("AddDatabase"), DISPID(6));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = Name /*[VT_BSTR:0]*/;
  _args[3] = IDDB /*[VT_I4:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, 
                                      int* Connect/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("DatabaseConnect"), DISPID(8));
  TAutoArgs<2> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDDB /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Connect /*[VT_INT:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> int __fastcall
IClientsDispT<T>::get_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/)
{
  int Connect;
  this->get_DatabaseConnect(IDC, IDDB, (int*)&Connect);
  return Connect;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::set_DatabaseConnect(long IDC/*[in]*/, long IDDB/*[in]*/, int Connect/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("DatabaseConnect"), DISPID(8));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDDB /*[VT_I4:0]*/;
  _args[3] = Connect /*[VT_INT:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::set_SetCommandText(long IDC/*[in]*/, long IDDB/*[in]*/, BSTR Param3/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("SetCommandText"), DISPID(7));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDDB /*[VT_I4:0]*/;
  _args[3] = Param3 /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::CommandExec(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("CommandExec"), DISPID(9));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDDB /*[VT_I4:0]*/;
  _args[3] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::MergeLogins(long IDC/*[in]*/, long IDDB/*[in]*/, int* OK/*[out]*/, 
                              int* Wait/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("MergeLogins"), DISPID(10));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDDB /*[VT_I4:0]*/;
  _args[3] = OK /*[VT_INT:1]*/;
  _args[4] = Wait /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::VerifyConnect(long IDC/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("VerifyConnect"), DISPID(11));
  TAutoArgs<1> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::get_NetError(VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("NetError"), DISPID(12));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
IClientsDispT<T>::get_NetError(void)
{
  VARIANT_BOOL Value;
  this->get_NetError((VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::PrepareReadMetod(long IDC/*[in]*/, BSTR NameDatabase/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("PrepareReadMetod"), DISPID(13));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = NameDatabase /*[VT_BSTR:0]*/;
  _args[3] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::MergeNodeBranch(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                  BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                  BSTR NameDatabase2/*[in]*/, BSTR NameTable/*[in]*/, 
                                  BSTR NameField/*[in]*/, BSTR NameKey/*[in]*/, BSTR Name/*[in]*/, 
                                  int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("MergeNodeBranch"), DISPID(14));
  TAutoArgs<10> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = NameDatabase1 /*[VT_BSTR:0]*/;
  _args[3] = NameNode /*[VT_BSTR:0]*/;
  _args[4] = NameBranch /*[VT_BSTR:0]*/;
  _args[5] = NameDatabase2 /*[VT_BSTR:0]*/;
  _args[6] = NameTable /*[VT_BSTR:0]*/;
  _args[7] = NameField /*[VT_BSTR:0]*/;
  _args[8] = NameKey /*[VT_BSTR:0]*/;
  _args[9] = Name /*[VT_BSTR:0]*/;
  _args[10] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::MergeNodeBranch_Sm(long IDC/*[in]*/, BSTR NameDatabase1/*[in]*/, 
                                     BSTR NameNode/*[in]*/, BSTR NameBranch/*[in]*/, 
                                     int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("MergeNodeBranch_Sm"), DISPID(15));
  TAutoArgs<5> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = NameDatabase1 /*[VT_BSTR:0]*/;
  _args[3] = NameNode /*[VT_BSTR:0]*/;
  _args[4] = NameBranch /*[VT_BSTR:0]*/;
  _args[5] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::MergeZn(long IDC/*[in]*/, BSTR Database1/*[in]*/, BSTR Database2/*[in]*/, 
                          int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("MergeZn"), DISPID(16));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = Database1 /*[VT_BSTR:0]*/;
  _args[3] = Database2 /*[VT_BSTR:0]*/;
  _args[4] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::SaveMetod(long IDC/*[in]*/, BSTR Database/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("SaveMetod"), DISPID(17));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = Database /*[VT_BSTR:0]*/;
  _args[3] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::SavePodr(long IDC/*[in]*/, BSTR DB1/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("SavePodr"), DISPID(18));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = DB1 /*[VT_BSTR:0]*/;
  _args[3] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::SaveSit(long IDC/*[in]*/, BSTR DB1/*[in]*/, BSTR DB2/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("SaveSit"), DISPID(20));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = DB1 /*[VT_BSTR:0]*/;
  _args[3] = DB2 /*[VT_BSTR:0]*/;
  _args[4] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::Visible()
{
  _TDispID _dispid(*this, OLETEXT("Visible"), DISPID(21));
  return OleFunction(_dispid);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::MergeAspectsMainSpec(long IDC/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("MergeAspectsMainSpec"), DISPID(22));
  TAutoArgs<2> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::PrepareLoadAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, long Podr/*[in]*/
                                     , long Width1/*[in]*/, long Width2/*[in]*/, long Width3/*[in]*/
                                     , long Width4/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("PrepareLoadAspects"), DISPID(23));
  TAutoArgs<8> _args;
  _args[1] = NameDatabase /*[VT_BSTR:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = Podr /*[VT_I4:0]*/;
  _args[4] = Width1 /*[VT_I4:0]*/;
  _args[5] = Width2 /*[VT_I4:0]*/;
  _args[6] = Width3 /*[VT_I4:0]*/;
  _args[7] = Width4 /*[VT_I4:0]*/;
  _args[8] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::get_Block(long IDC/*[in]*/, int* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Block"), DISPID(19));
  TAutoArgs<1> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_INT:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> int __fastcall
IClientsDispT<T>::get_Block(long IDC/*[in]*/)
{
  int Value;
  this->get_Block(IDC, (int*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::set_Block(long IDC/*[in]*/, int* Value/*[in,out]*/)
{
  _TDispID _dispid(*this, OLETEXT("Block"), DISPID(19));
  TAutoArgs<2> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = Value /*[VT_INT:1]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::PrepareMergeAspects(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                      long NumLogin/*[in]*/, long W1/*[in]*/, long W2/*[in]*/, 
                                      long W3/*[in]*/, long W4/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("PrepareMergeAspects"), DISPID(24));
  TAutoArgs<8> _args;
  _args[1] = NameDatabase /*[VT_BSTR:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = NumLogin /*[VT_I4:0]*/;
  _args[4] = W1 /*[VT_I4:0]*/;
  _args[5] = W2 /*[VT_I4:0]*/;
  _args[6] = W3 /*[VT_I4:0]*/;
  _args[7] = W4 /*[VT_I4:0]*/;
  _args[8] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::WriteDiary(BSTR Comp/*[in]*/, BSTR Login/*[in]*/, BSTR Type/*[in]*/, 
                             BSTR Name/*[in]*/, BSTR Prim/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("WriteDiary"), DISPID(25));
  TAutoArgs<5> _args;
  _args[1] = Comp /*[VT_BSTR:0]*/;
  _args[2] = Login /*[VT_BSTR:0]*/;
  _args[3] = Type /*[VT_BSTR:0]*/;
  _args[4] = Name /*[VT_BSTR:0]*/;
  _args[5] = Prim /*[VT_BSTR:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::get_LicenseCount(BSTR DBName/*[in]*/, long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("LicenseCount"), DISPID(26));
  TAutoArgs<1> _args;
  _args[1] = DBName /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
IClientsDispT<T>::get_LicenseCount(BSTR DBName/*[in]*/)
{
  long Value;
  this->get_LicenseCount(DBName, (long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::PrepareMergeAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, 
                                       long NumLogin/*[in]*/, long W1/*[in]*/, long W2/*[in]*/, 
                                       long W3/*[in]*/, long W4/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("PrepareMergeAspectsH"), DISPID(28));
  TAutoArgs<8> _args;
  _args[1] = NameDatabase /*[VT_BSTR:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = NumLogin /*[VT_I4:0]*/;
  _args[4] = W1 /*[VT_I4:0]*/;
  _args[5] = W2 /*[VT_I4:0]*/;
  _args[6] = W3 /*[VT_I4:0]*/;
  _args[7] = W4 /*[VT_I4:0]*/;
  _args[8] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::PrepareLoadAspectsH(BSTR NameDatabase/*[in]*/, long IDC/*[in]*/, long Podr/*[in]*/
                                      , long Width1/*[in]*/, long Width2/*[in]*/, 
                                      long Width3/*[in]*/, long Width4/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("PrepareLoadAspectsH"), DISPID(29));
  TAutoArgs<8> _args;
  _args[1] = NameDatabase /*[VT_BSTR:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = Podr /*[VT_I4:0]*/;
  _args[4] = Width1 /*[VT_I4:0]*/;
  _args[5] = Width2 /*[VT_I4:0]*/;
  _args[6] = Width3 /*[VT_I4:0]*/;
  _args[7] = Width4 /*[VT_I4:0]*/;
  _args[8] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IClientsDispT<T>::MergeAspectsMainSpecH(long IDC/*[in]*/, int* Ret/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("MergeAspectsMainSpecH"), DISPID(30));
  TAutoArgs<2> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = Ret /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// SmartIntf: TCOMITables
// Interface: ITables
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMITablesT<T>::CreateTable(long IDC/*[in]*/, long IDDB/*[in]*/, long IDF/*[in]*/, 
                             long* IDT/*[out]*/)
{
  return (*this)->CreateTable(IDC, IDDB, IDF, IDT);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::DeleteTable(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, int* OK/*[out]*/)
{
  return (*this)->DeleteTable(IDC, IDF, IDT, OK);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::Active(VARIANT_BOOL Value/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                        long IDT/*[in]*/, int* OK/*[out]*/)
{
  return (*this)->Active(Value, IDC, IDF, IDT, OK);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 BSTR* Text/*[out,retval]*/)
{
  return (*this)->get_CommandText(IDC, IDF, IDT, Text);
}

template <class T> BSTR __fastcall
TCOMITablesT<T>::get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  BSTR Text = 0;
  OLECHECK(this->get_CommandText(, (BSTR*)&Text));
  return Text;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::set_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 BSTR Text/*[in]*/)
{
  return (*this)->set_CommandText(IDC, IDF, IDT, Text);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::Moving(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  return (*this)->Moving(Comand, IDC, IDF, IDT);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                             long IDT/*[in]*/, VARIANT_BOOL* Value/*[out,retval]*/)
{
  return (*this)->get_BOF_EOF(Comand, IDC, IDF, IDT, Value);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITablesT<T>::get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                             long IDT/*[in]*/)
{
  VARIANT_BOOL Value;
  OLECHECK(this->get_BOF_EOF(, (VARIANT_BOOL*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  return (*this)->get_FieldByName_Variant(FieldName, IDC, IDF, IDT, Value);
}

template <class T> VARIANT __fastcall
TCOMITablesT<T>::get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/)
{
  VARIANT Value;
  OLECHECK(this->get_FieldByName_Variant(, (VARIANT*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::set_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/, VARIANT Value/*[in]*/)
{
  return (*this)->set_FieldByName_Variant(FieldName, IDC, IDF, IDT, Value);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::EditingRecord(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                               long IDT/*[in]*/)
{
  return (*this)->EditingRecord(Comand, IDC, IDF, IDT);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 long* Value/*[out,retval]*/)
{
  return (*this)->get_RecordCount(IDC, IDF, IDT, Value);
}

template <class T> long __fastcall
TCOMITablesT<T>::get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  long Value;
  OLECHECK(this->get_RecordCount(, (long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                           long* Value/*[out,retval]*/)
{
  return (*this)->get_RecNo(IDC, IDF, IDT, Value);
}

template <class T> long __fastcall
TCOMITablesT<T>::get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  long Value;
  OLECHECK(this->get_RecNo(, (long*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::Move(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, long Step/*[in]*/)
{
  return (*this)->Move(IDC, IDF, IDT, Step);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                            BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, long SearchParam/*[in]*/, 
                            VARIANT_BOOL* OK/*[out,retval]*/)
{
  return (*this)->get_Locate(IDC, IDF, IDT, FieldName, Key, SearchParam, OK);
}

template <class T> VARIANT_BOOL __fastcall
TCOMITablesT<T>::get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                            BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, long SearchParam/*[in]*/)
{
  VARIANT_BOOL OK;
  OLECHECK(this->get_Locate(, (VARIANT_BOOL*)&OK));
  return OK;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::Delete(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  return (*this)->Delete(IDC, IDF, IDT);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                            long IDT/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  return (*this)->get_Fields(NumField, IDC, IDF, IDT, Value);
}

template <class T> VARIANT __fastcall
TCOMITablesT<T>::get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                            long IDT/*[in]*/)
{
  VARIANT Value;
  OLECHECK(this->get_Fields(, (VARIANT*)&Value));
  return Value;
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::set_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                            long IDT/*[in]*/, VARIANT Value/*[in]*/)
{
  return (*this)->set_Fields(NumField, IDC, IDF, IDT, Value);
}

template <class T> HRESULT __fastcall
TCOMITablesT<T>::get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 long* Value/*[out,retval]*/)
{
  return (*this)->get_FieldsCount(IDC, IDF, IDT, Value);
}

template <class T> long __fastcall
TCOMITablesT<T>::get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  long Value;
  OLECHECK(this->get_FieldsCount(, (long*)&Value));
  return Value;
}

// *********************************************************************//
// DispIntf:  ITables
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {3AF8D7F1-0DAB-415C-A063-2BCE1F071E24}
// *********************************************************************//
template <class T> HRESULT __fastcall
ITablesDispT<T>::CreateTable(long IDC/*[in]*/, long IDDB/*[in]*/, long IDF/*[in]*/, 
                             long* IDT/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("CreateTable"), DISPID(1));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDDB /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::DeleteTable(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, int* OK/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("DeleteTable"), DISPID(2));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  _args[4] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::Active(VARIANT_BOOL Value/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                        long IDT/*[in]*/, int* OK/*[out]*/)
{
  _TDispID _dispid(*this, OLETEXT("Active"), DISPID(3));
  TAutoArgs<5> _args;
  _args[1] = Value /*[VT_BOOL:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  _args[5] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 BSTR* Text/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("CommandText"), DISPID(4));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Text /*[VT_BSTR:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> BSTR __fastcall
ITablesDispT<T>::get_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  BSTR Text;
  this->get_CommandText(IDC, IDF, IDT, (BSTR*)&Text);
  return Text;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::set_CommandText(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 BSTR Text/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("CommandText"), DISPID(4));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  _args[4] = Text /*[VT_BSTR:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::Moving(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Moving"), DISPID(5));
  TAutoArgs<4> _args;
  _args[1] = Comand /*[VT_I4:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                             long IDT/*[in]*/, VARIANT_BOOL* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("BOF_EOF"), DISPID(6));
  TAutoArgs<4> _args;
  _args[1] = Comand /*[VT_I4:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITablesDispT<T>::get_BOF_EOF(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                             long IDT/*[in]*/)
{
  VARIANT_BOOL Value;
  this->get_BOF_EOF(Comand, IDC, IDF, IDT, (VARIANT_BOOL*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/
                                         , long IDT/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("FieldByName_Variant"), DISPID(7));
  TAutoArgs<4> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITablesDispT<T>::get_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                                         long IDT/*[in]*/)
{
  VARIANT Value;
  this->get_FieldByName_Variant(FieldName, IDC, IDF, IDT, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::set_FieldByName_Variant(BSTR FieldName/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/
                                         , long IDT/*[in]*/, VARIANT Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("FieldByName_Variant"), DISPID(7));
  TAutoArgs<5> _args;
  _args[1] = FieldName /*[VT_BSTR:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  _args[5] = Value /*[VT_VARIANT:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::EditingRecord(long Comand/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                               long IDT/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("EditingRecord"), DISPID(8));
  TAutoArgs<4> _args;
  _args[1] = Comand /*[VT_I4:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("RecordCount"), DISPID(10));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
ITablesDispT<T>::get_RecordCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  long Value;
  this->get_RecordCount(IDC, IDF, IDT, (long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                           long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("RecNo"), DISPID(9));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
ITablesDispT<T>::get_RecNo(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  long Value;
  this->get_RecNo(IDC, IDF, IDT, (long*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::Move(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, long Step/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Move"), DISPID(11));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  _args[4] = Step /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                            BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, long SearchParam/*[in]*/, 
                            VARIANT_BOOL* OK/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Locate"), DISPID(12));
  TAutoArgs<6> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  _args[4] = FieldName /*[VT_BSTR:0]*/;
  _args[5] = Key /*[VT_BSTR:0]*/;
  _args[6] = SearchParam /*[VT_I4:0]*/;
  return OutRetValSetterPtr(OK /*[VT_BOOL:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT_BOOL __fastcall
ITablesDispT<T>::get_Locate(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                            BSTR FieldName/*[in]*/, BSTR Key/*[in]*/, long SearchParam/*[in]*/)
{
  VARIANT_BOOL OK;
  this->get_Locate(IDC, IDF, IDT, FieldName, Key, SearchParam, (VARIANT_BOOL*)&OK);
  return OK;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::Delete(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Delete"), DISPID(13));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                            long IDT/*[in]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Fields"), DISPID(14));
  TAutoArgs<4> _args;
  _args[1] = NumField /*[VT_I4:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITablesDispT<T>::get_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                            long IDT/*[in]*/)
{
  VARIANT Value;
  this->get_Fields(NumField, IDC, IDF, IDT, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::set_Fields(long NumField/*[in]*/, long IDC/*[in]*/, long IDF/*[in]*/, 
                            long IDT/*[in]*/, VARIANT Value/*[in]*/)
{
  _TDispID _dispid(*this, OLETEXT("Fields"), DISPID(14));
  TAutoArgs<5> _args;
  _args[1] = NumField /*[VT_I4:0]*/;
  _args[2] = IDC /*[VT_I4:0]*/;
  _args[3] = IDF /*[VT_I4:0]*/;
  _args[4] = IDT /*[VT_I4:0]*/;
  _args[5] = Value /*[VT_VARIANT:0]*/;
  return OlePropertyPut(_dispid, _args);
}

template <class T> HRESULT __fastcall
ITablesDispT<T>::get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/, 
                                 long* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("FieldsCount"), DISPID(15));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = IDT /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Value /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
ITablesDispT<T>::get_FieldsCount(long IDC/*[in]*/, long IDF/*[in]*/, long IDT/*[in]*/)
{
  long Value;
  this->get_FieldsCount(IDC, IDF, IDT, (long*)&Value);
  return Value;
}

// *********************************************************************//
// SmartIntf: TCOMIForm
// Interface: IForm
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIFormT<T>::RegForm(long IDC/*[in]*/, BSTR NameForm/*[in]*/, long* IDF/*[out]*/, 
                       int* OK/*[in,out,opt]*/)
{
  return (*this)->RegForm(IDC, NameForm, IDF, OK);
}

template <class T> HRESULT __fastcall
TCOMIFormT<T>::UnregForm_IDF(long IDC/*[in]*/, long IDF/*[in]*/, int* OK/*[in,out,opt]*/)
{
  return (*this)->UnregForm_IDF(IDC, IDF, OK);
}

template <class T> HRESULT __fastcall
TCOMIFormT<T>::UnregForm_Name(long IDC/*[in]*/, BSTR NameForm/*[in]*/, int* OK/*[in,out,opt]*/)
{
  return (*this)->UnregForm_Name(IDC, NameForm, OK);
}

template <class T> HRESULT __fastcall
TCOMIFormT<T>::UnregAll(long IDC/*[in]*/, int* OK/*[in,out,opt]*/)
{
  return (*this)->UnregAll(IDC, OK);
}

template <class T> HRESULT __fastcall
TCOMIFormT<T>::get_CountForm(long IDC/*[in]*/, long* Count/*[out,retval]*/)
{
  return (*this)->get_CountForm(IDC, Count);
}

template <class T> long __fastcall
TCOMIFormT<T>::get_CountForm(long IDC/*[in]*/)
{
  long Count;
  OLECHECK(this->get_CountForm(, (long*)&Count));
  return Count;
}

// *********************************************************************//
// DispIntf:  IForm
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {BB8D688F-AD99-41A7-8BFC-067831945105}
// *********************************************************************//
template <class T> HRESULT __fastcall
IFormDispT<T>::RegForm(long IDC/*[in]*/, BSTR NameForm/*[in]*/, long* IDF/*[out]*/, 
                       int* OK/*[in,out,opt]*/)
{
  _TDispID _dispid(*this, OLETEXT("RegForm"), DISPID(1));
  TAutoArgs<4> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = NameForm /*[VT_BSTR:0]*/;
  _args[3] = IDF /*[VT_I4:1]*/;
  _args[4] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IFormDispT<T>::UnregForm_IDF(long IDC/*[in]*/, long IDF/*[in]*/, int* OK/*[in,out,opt]*/)
{
  _TDispID _dispid(*this, OLETEXT("UnregForm_IDF"), DISPID(2));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = IDF /*[VT_I4:0]*/;
  _args[3] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IFormDispT<T>::UnregForm_Name(long IDC/*[in]*/, BSTR NameForm/*[in]*/, int* OK/*[in,out,opt]*/)
{
  _TDispID _dispid(*this, OLETEXT("UnregForm_Name"), DISPID(3));
  TAutoArgs<3> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = NameForm /*[VT_BSTR:0]*/;
  _args[3] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IFormDispT<T>::UnregAll(long IDC/*[in]*/, int* OK/*[in,out,opt]*/)
{
  _TDispID _dispid(*this, OLETEXT("UnregAll"), DISPID(4));
  TAutoArgs<2> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  _args[2] = OK /*[VT_INT:1]*/;
  return OleFunction(_dispid, _args);
}

template <class T> HRESULT __fastcall
IFormDispT<T>::get_CountForm(long IDC/*[in]*/, long* Count/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("CountForm"), DISPID(5));
  TAutoArgs<1> _args;
  _args[1] = IDC /*[VT_I4:0]*/;
  return OutRetValSetterPtr(Count /*[VT_I4:1]*/, _args, OlePropertyGet(_dispid, _args));
}

template <class T> long __fastcall
IFormDispT<T>::get_CountForm(long IDC/*[in]*/)
{
  long Count;
  this->get_CountForm(IDC, (long*)&Count);
  return Count;
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : Clients
// Interface: TCOMIClients
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIClients, IClients, &CLSID_Clients, &IID_IClients> CoClients;

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : Tables
// Interface: TCOMITables
// *********************************************************************//
typedef TCoClassCreatorT<TCOMITables, ITables, &CLSID_Tables, &IID_ITables> CoTables;

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : Form
// Interface: TCOMIForm
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIForm, IForm, &CLSID_Form, &IID_IForm> CoForm;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


};     // namespace Server_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Server_tlb;
#endif

#pragma option pop

#endif // Server_TLBH
